name: lt_toolbox
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - polars
  - plotly
  - numpy
  - cython
  - matplotlib
  - xarray
  - scipy
  - pygeos
  - proj
  - cartopy
  - zarr