name: lt_toolbox
channels:
  - conda-forge
dependencies:
  - python=3.9
  - polars
  - plotly
  - numpy
  - cython
  - matplotlib
  - xarray
  - pip>=22.2.2
  - scipy
  - pygeos
  - proj
  - cartopy
  - dask
pip:
  - git+https://github.com/oj-tooth/lt_toolbox.git