# https://www.mkdocs.org/user-guide/configuration/

# Project information
site_name: LT-Toolbox
site_url: https://oj-tooth.github.io/lt_toolbox/
repo_url: https://github.com/oj_tooth/lt_toolbox/
repo_name: lt_toolbox


nav:
- Welcome: index.md
